### ISSUE TITLE
When two or more statistics are converted, not all statistics are displayed.

### ISSUE THREAD

**Issue by Ikstoi** [Plagiatus/MCStatsToExcel#2] opened 2023-11-06 13:11 UTC
There seems to be a priority between 2 stats when you convert them into Excel. 

Example: Suppose I have killed 0 guardians on one world, but 5 on another. The world with 0 killed does not display the guardian killed stat. Despite the fact that 5 guardians have been killed in the other world.

It looks like it's prioritizing the stat with a larger number for the first digit. ¯\_(ツ)_/¯

![The_First_Stat_With_5_Killed](https://github.com/Plagiatus/MCStatsToExcel/assets/78237731/35e9951f-30d9-4569-8731-8e183577f9df)

![After_I_Add_The_Stat_It_Seems_To_Prioritize](https://github.com/Plagiatus/MCStatsToExcel/assets/78237731/69a84854-c378-44cc-a3a4-4a03857f4168)

**Comment by Plagiatus** [comment] 2023-11-06 15:17
Yes, the individual conversions are independant from each other. And the game only records stats that are above 0, everything else is not included in the stat files and thus also does not get exported to the excel sheets.

---------

I'm not sure I understand your issue fully though: Are you combining two sets of stats from different worlds but from the same player? How are you doing that exactly? Because the input is based on the player uuid which is in the file name so you shouldn't be able to do that.  
Or are you trying to compare two different players from different worlds? Say two players playing in singleplayer and now you want to combine both of their stats into a single sheet, but some stats are seemingly not displayed?

could you provide the input files so I can try to reproduce the issue?

**Comment by Ikstoi** [comment] 2023-11-07 02:51
My goal was to combine 2 stats from an old server I played on, and a ssp world.
I was going to use Excels sum feature.

I can attach the two statistics files.

[9a1a093b-62a6-4896-bc75-4d1582ade64f.json](https://github.com/Plagiatus/MCStatsToExcel/files/13275102/9a1a093b-62a6-4896-bc75-4d1582ade64f.json)

[7f197618-32c2-4876-841b-cea29bd58cae.json](https://github.com/Plagiatus/MCStatsToExcel/files/13275106/7f197618-32c2-4876-841b-cea29bd58cae.json)

**Comment by Plagiatus** [comment] 2023-11-09 20:29
I had a feeling I've seen this before. And yes, I actually had implemented a fix for this almost immediately after the initial release. Then I drafted a release for this fix but apparently never published it.

Welp, I found another issue (the UUIDs not getting resolved to names anymore), so fixed that, too, and made a new release.

So, this issue is fixed in [Release 0.0.2](https://github.com/Plagiatus/MCStatsToExcel/releases/tag/0.0.2), please use that one.

**Closed as completed by Plagiatus** 2023-11-09 20:29 UTC
